# Generated by Django 4.2.4 on 2023-08-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choise_gender',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], default='male', max_length=20),
        ),
    ]
