# Generated by Django 4.2.4 on 2023-08-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_choise_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='choise_gender',
            new_name='gender',
        ),
    ]
