# Generated by Django 4.2.4 on 2023-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_choise_gender_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mails',
            field=models.BooleanField(default=False),
        ),
    ]
